name: mytransport
description: MyTransport Malaysia - AI-Powered Transit & Travel Partner
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1

  # Networking
  http: ^1.2.1
  archive: ^3.6.1

  # Maps
  google_maps_flutter: ^2.9.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # GPS / location
  geolocator: ^13.0.2
  geocoding: ^4.0.0

  # Camera + Compass AR fallback (works on all devices)
  camera: ^0.10.6
  flutter_compass: ^0.8.0
  sensors_plus: ^6.0.0

  # Local storage for auth token
  shared_preferences: ^2.3.2
  socket_io_client: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
